apiVersion: v1
kind: ConfigMap
metadata:
  name: nexa-scheduler-config
  namespace: nexa-system
  labels:
    app.kubernetes.io/name: nexa-scheduler
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: nexa-scheduler
        plugins:
          filter:
            enabled:
              - name: NexaRegion
              - name: NexaPrivacy
          preFilter:
            enabled:
              - name: NexaAudit
          score:
            enabled:
              - name: NexaRegion
                weight: 50
              - name: NexaPrivacy
                weight: 50
          postFilter:
            enabled:
              - name: NexaAudit
          postBind:
            enabled:
              - name: NexaAudit
