FROM golang:1.24 AS builder

WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /nexa-webhook ./cmd/webhook

FROM gcr.io/distroless/static:nonroot

COPY --from=builder /nexa-webhook /nexa-webhook

USER 65532:65532

ENTRYPOINT ["/nexa-webhook"]
