apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexa-maa-adapter.fullname" . }}
  labels:
    {{- include "nexa-maa-adapter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.adapter.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.adapter.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "nexa-maa-adapter.selectorLabels" . | nindent 4 }}
